### ISSUE TITLE
私有仓库

### ISSUE THREAD

**Issue by 4o4tech** [jizhantech/jizhan-supply-chain-instock#1]
杨总，搞个私有仓库，这样谁都可以看到不安全，谁都可以把公司的后台 clone 过去；公司财产要保护的……

有免费的方法建立私有仓，申请 github学生优惠或者去 code.aliyun.com  新建一个私有的项目，把自己的小伙伴都拉进去。

**Comment by xdyangchn** [comment]
谢张总提醒，强烈采纳建议！
